### ISSUE TITLE
what-input.min.js 404

### ISSUE THREAD

**Issue by leifjohn** [JeremyEnglert/JointsWP-Documentation#5]
I have noticed every time I start a new JointsWP project I receive a 404 because it cannot find the what-input.min.js file in the directory:

/vendor/what-input/what-input.min.js

because it does not exist there. You need to edit the enqueue-scripts.php file and update the directory to:

/vendor/what-input/dist/what-input.min.js

**Comment by JeremyEnglert** [comment]
Hmmm. Are you using an older version of the theme?

It appears to enqueue from the correct location: https://github.com/JeremyEnglert/JointsWP/blob/master/assets/functions/enqueue-scripts.php
