### ISSUE TITLE
NAV loads as li with no css for one second

### ISSUE THREAD

**Issue by joeyjosay** [JeremyEnglert/JointsWP-Documentation#7]
As i click in the nav the new page loads with the nav as li then a second later the nav turns to the proper css nav bar. Any ideas why?

**Comment by JeremyEnglert** [comment]
http://foundation.zurb.com/sites/docs/responsive-navigation.html#preventing-fouc

**Comment by JeremyEnglert** [comment]
Let me know if that doesn't fix the issue.
